# Generated by Django 3.0.8 on 2020-07-28 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='cate_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
