# Generated by Django 3.0.8 on 2020-07-28 07:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_products_cate_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
